# Generated by Django 5.1.3 on 2024-11-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=90)),
                ('age', models.IntegerField()),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=90)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('aadhaar_card_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('voter', 'Voter'), ('admin', 'Admin')], default='voter', max_length=80)),
                ('is_voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='testapp.candidatemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='testapp.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='candidatemodel',
            name='votes',
            field=models.ManyToManyField(related_name='voted_candidates', through='testapp.Vote', to='testapp.usermodel'),
        ),
    ]
